# Generated by Django 5.2.6 on 2025-09-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
